#!/bin/sh

if ! type git >/dev/null 2>&1; then
  printf "\nNot found git, run command\n\n"
  printf "    \033[36mbrew install git\033[0m\n"
  exit 1
fi

set -eux

REPO_NAME=${1:-terraform-provider-name}
git clone --depth 1 https://github.com/tmknom/template-terraform-module.git "${REPO_NAME}"

cd "${REPO_NAME}"
rm -rf install .git
mv terraform.mk .terraform.mk

REGISTRY_PATH=$(echo "${REPO_NAME}" | awk -F- '{print substr($0, index($0, $3))"/"$2}')
sed -i "" -e "s#name/provider#${REGISTRY_PATH}#g" README.md
sed -i "" -e "s/template-terraform-module/${REPO_NAME}/g" README.md
sed -i "" -e "s/include terraform.mk/include .terraform.mk/g" Makefile

# remove code without comment
find . -type f -name '*.tf' -path "./*" -not -path "**/.terraform/*" | xargs -I {} sed -i "" -e "/^[^#]/d" -e "/^$/d" {}

git init
git add .
git commit -m "Initial commit" -m "Based on https://github.com/tmknom/template-terraform-module"

set +x
printf "\nInstall success, run command\n\n"
printf "    \033[36mcd %s && make install\033[0m\n" "${REPO_NAME}"
